language: nix

# Update from the default nix version on Travis CI (2.0.4), which does not
# handle SRI hashes: https://github.com/NixOS/nixpkgs/issues/89275
nix: 2.3.5

jobs:
  include:
    - name: nixpkgs-unstable
      env: NIX_PATH=nixpkgs=https://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz
    - name: nixos-19.09
      env: NIX_PATH=nixpkgs=https://nixos.org/channels/nixos-19.09/nixexprs.tar.xz

script: nix-shell --run 'make test'
